### ISSUE TITLE
Token refresh can crash

### ISSUE THREAD

**Issue by fdietze** [fun-stack/sdk-scala#14]
The request can return the following payload:
```
{"error":"invalid_grant"}
```

In this case, the cast to `TokenResponse` is invalid and acessing the members crash the app.

https://github.com/fun-stack-org/fun-stack-scala/blob/c4fb4dbcde972e591de72ff823eb50231ccbd4d9/web/src/main/scala/Auth.scala#L186

**Comment by cornerman** [comment]
Do we know, when this can happen? Imho, this should only happen if cognito is not properly configured.

**Comment by fdietze** [comment]
I had this with  old session data. Once I cleared the site data, it worked.

**Comment by cornerman** [comment]
Ok. Then we need to catch that one!

**Comment by fdietze** [comment]
Just happened again...
Does it happen once the `AccessToken` expires and needs to be refreshed?

**Comment by fdietze** [comment]
To reproduce, you could probably set the cognito expiry time to 5min.

**Comment by cornerman** [comment]
I think there are two things we need to handle: the access token is wrong (that is the code you have in the url when being redirected from cognito signin, which could be in the browswr history. Or the refresh token expired, which is stored in localstorage and used for getting a valid access token on app startup - and we use it to get a new token when the access token expires.

**Comment by fdietze** [comment]
It happened again:

![2022-01-19_23-40-48_1858x1211](https://user-images.githubusercontent.com/1186516/150230049-76e1223f-e59e-4a56-af95-790c430f6b2b.png)
![2022-01-19_23-45-12_2105x297](https://user-images.githubusercontent.com/1186516/150230595-1612480d-bf40-48e0-9c45-25e86363a10b.png)
![2022-01-19_23-43-25_2113x408](https://user-images.githubusercontent.com/1186516/150230596-06f6c238-340f-478e-a12b-f0b74830f30e.png)
![2022-01-19_23-46-20_1666x779](https://user-images.githubusercontent.com/1186516/150230684-d008b4ba-2d43-45e8-9de1-a3fc32a9aad4.png)
![2022-01-19_23-46-13_1666x1058](https://user-images.githubusercontent.com/1186516/150230688-393edd9f-3cce-4df2-918b-0a2fed0d3272.png)
