### ISSUE TITLE
HTTP: better return code

### ISSUE THREAD

**Issue by fdietze** [fun-stack/sdk-scala#90]
Currently, failed HTTP requests return 404, but it should probably be something like 500 or 403, depending on the case.

https://github.com/fun-stack/fun-stack-scala/blob/30678dd90fa4ed744466125d5af57a82cecf29b2/lambdaHttp/src/main/scala/Handler.scala#L100

**Comment by cornerman** [comment]
Will probably be fixed with #100

**Comment by cornerman** [comment]
Using aws tapir integration now
